version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: laborlens_db
    environment:
      POSTGRES_USER: laborlens
      POSTGRES_PASSWORD: flock6454
      POSTGRES_DB: laborlens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: